name: CI
on: push
jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run tests
        run: deno test --allow-env --allow-read=. --allow-net=api.github.com,0.0.0.0,localhost
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: dprint-plugins
          entrypoint: main.ts
